blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ ç¾¤èŠäº¤æµ
    url: ç‚¹å‡»é“¾æ¥åŠ å…¥ç¾¤èŠã€Azur Lane test by xialuolinekoã€‘ï¼šhttps://qm.qq.com/q/kxLs5JVTBC
    about: å¦‚æœæœ‰å…¶ä»–é—®é¢˜ï¼Œè¯·åŠ ç¾¤è¯¢é—®ã€‚
